contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nfstuff channel"
    url: https://nfcore.slack.com/channels/nfstuff
    about: Discussion about the nf-core/nfstuff pipeline
